### ISSUE TITLE
Install trips over wp-config.php not existing from fresh install

### ISSUE THREAD

**Issue by bradbaris** [micjamking/generator-microcebus#6]
Not sure if I screwed up a simple thing, because it's a simple error. Just thought I'd bring it up.

```
Cloning theme from https://github.com/ikayzo/_s.git ...
{ [Error: Command failed: /bin/sh -c wp core config --dbname="<database>" --dbuser="<user>" --dbpass="<password>"
Error: The 'wp-config.php' file already exists.
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c wp core config --dbname="<database>" --dbuser="<user>" --dbpass="<password>' }

Making our custom theme the default theme...
fs.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy

Error: ENOENT, no such file or directory './wp-config.php'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at replacizeFileSync (/usr/local/lib/node_modules/generator-microcebus/node_modules/replace/replace.js:121:22)
    at module.exports (/usr/local/lib/node_modules/generator-microcebus/node_modules/replace/replace.js:64:13)
    at null.<anonymous> (/usr/local/lib/node_modules/generator-microcebus/app/index.js:194:9)
    at helpIfError (/usr/local/lib/node_modules/generator-microcebus/node_modules/wp-cli/lib/utils.js:64:9)
    at /usr/local/lib/node_modules/generator-microcebus/node_modules/wp-cli/lib/utils.js:77:4
    at ChildProcess.exithandler (child_process.js:758:5)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
```

**Comment by micjamking** [comment]
@bradbaris thanks for catching this. I'll try to replicate it this weekend and see what's going on.
